Blog_App/urls.py
from django.urls import path
from . import views

app_name = 'Blog_App'

urlpatterns = [
    path('', views.home, name="home"),
    path('contact/', views.contact, name="contact"),
    path('blogs/', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit/<slug>/', views.UpdateBlog.as_view(), name='edit_blog'),

]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
# for MEDIA
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('Login_App.urls')),
    path('', include('Blog_App.urls')),
    # path('', views.Index, name='index' )
]

# FOR MEDIA
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Blog_App/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name="Put a Title")
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = RichTextField(blank=True, null=True)
    blog_image = models.ImageField(upload_to='blog_image', verbose_name='Image')
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publish_date',]

    def __str__(self):
        return self.blog_title


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-comment_date',]


    def __str__(self):
        return self.comment


class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liked_user')

    def __str__(self):
        return self.user , " likes " , self.blog

Blog_App/forms.py
from django import forms
from Blog_App.models import Blog, Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('comment',)

Blog_App/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView, View, TemplateView, DeleteView
from Blog_App.models import Blog, Comment, Likes
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid #unique id generate
from Blog_App.forms import CommentForm
from django.core.paginator import Paginator
# Create your views here.

# def blog_list(request):
#     return render(request, 'Blog_App/blog_list.html', context={})

# def home(request):
#     return render(request, 'Blog_App/home.html', context={})

# def home(request):
#     blogs = Blog.objects.order_by('-publish_date')[:3]  # get the 3 most recent blogs
#     context = {'blogs': blogs}
#     return render(request, 'Blog_App/home.html', context)

#after using paginator
def home(request):
    blog_list = Blog.objects.order_by('-publish_date')
    paginator = Paginator(blog_list, 4)  # Display 3 blogs per page
    page = request.GET.get('page')
    blogs = paginator.get_page(page)
    context = {'blogs': blogs}
    return render(request, 'Blog_App/home.html', context)

#BLOG LIST
class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'Blog_App/blog_list.html'
    # queryset = Blog.objects.order_by('-publish_date')

# BLOG CREATE
class CreateBlog(CreateView, LoginRequiredMixin):
    model = Blog
    template_name = 'Blog_App/create_blog.html'
    fields = ('blog_title', 'blog_content', 'blog_image')

    # non mentioned items generate
    def form_valid(self,form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(' ', '-') + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('Blog_App:home'))

#BLOG DETAILS
@login_required
def blog_details(request,slug):
    blog = Blog.objects.get(slug=slug)  #// my slug = published slug
    comment_form = CommentForm()
    already_liked = Likes.objects.filter(blog=blog, user=request.user)
    if already_liked:
        liked = True
    else:
        liked = False    
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user #comment form user
            comment.blog = blog #this blog
            comment.save()
            return HttpResponseRedirect(reverse('Blog_App:blog_details', kwargs={'slug':slug} ))

    return render(request, 'Blog_App/blog_details.html', context={'blog':blog, 'comment_form':comment_form, 'liked':liked})



#LIKED
@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked_post = Likes(blog=blog, user=user) #new object create
        liked_post.save()
    return HttpResponseRedirect(reverse('Blog_App:blog_details', kwargs={'slug':blog.slug} ))

#UNLIKED
@login_required
def unliked(request,pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('Blog_App:blog_details', kwargs={'slug':blog.slug} ))


#MY BLOGS
class MyBlogs(LoginRequiredMixin,TemplateView):
    # context_object_name= 'myblogs'
    template_name = "Blog_App/my_blogs.html"
    
class UpdateBlog(LoginRequiredMixin, UpdateView):
    model= Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name= 'Blog_App/edit_blog.html'
    
    def get_success_url(self, **kwargs):
           return reverse_lazy('Blog_App:blog_details', kwargs={'slug':self.object.slug})

def contact(request):
    return render(request, 'Blog_App/contact.html', context={})    

templates/Blog_App/blog_details.html
{% extends 'layouts/base.html' %}
<!-- {% load custom_filters %} -->
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock title_block %}

{% block body_block %}

  <!--================ Start Blog Post Area =================-->
  <section class="blog-post-area section-margin">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
            <div class="main_blog_details">
                <img class="img-fluid" src="/media/{{blog.blog_image}}" alt="">
                <a href="#"><h4>{{blog.blog_title}}</h4></a>
                <div class="user_details">
                  <div class="float-left">
                    <a href="#">Lifestyle</a>
                    <a href="#">Gadget</a>
                  </div>
                  <div class="float-right mt-sm-0 mt-3">
                    <div class="media">
                      <div class="media-body">
                        <h2>Posted By: @{{blog.author}}</h2>
                        <h6><i>Published On: {{blog.publish_date}}</i></h6>
                        <h6><i>Updated On: {{blog.update_date}}</i></h6>
                        <h6><i>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} Comments</i></h6>
                      </div>
                      <!-- <div class="d-flex">
                        <img width="42" height="42" src="img/blog/user-img.png" alt="">
                      </div> -->
                    </div>
                  </div>
                </div>
                <p> {{blog.blog_content|safe}}</p>

                
               <div class="news_d_footer flex-column flex-sm-row">
                {% if not liked %}
                 <a href="{% url 'Blog_App:liked_post' pk=blog.pk %}"><span class="align-middle mr-2"><i class="ti-heart-broken"></i></span>{{blog.liked_blog.count}} Likes this</a>

                {% else %}
                <a href="{% url 'Blog_App:unliked_post' pk=blog.pk %}">
                    <span class="align-middle mr-2"><i class="ti-heart"></i></span>{{blog.liked_blog.count}} Likes this 
                </a>
                {% endif %}
                 <a class="justify-content-sm-center ml-sm-auto mt-sm-0 mt-2" href="#"><span class="align-middle mr-2"><i class="ti-themify-favicon"></i></span>You have {{blog.blog_comment.count}} Comments</a>
                 <div class="news_socail ml-sm-auto mt-sm-0 mt-2">
               <a href="#"><i class="fab fa-facebook-f"></i></a>
               <a href="#"><i class="fab fa-twitter"></i></a>
               <a href="#"><i class="fab fa-dribbble"></i></a>
               <a href="#"><i class="fab fa-behance"></i></a>


             </div>
             
               </div>
              </div>
          

          <!-- <div class="navigation-area">
                  <div class="row">
                      <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                          <div class="thumb">
                              <a href="#"><img class="img-fluid" src="img/blog/prev.jpg" alt=""></a>
                          </div>
                          <div class="arrow">
                              <a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
                          </div>
                          <div class="detials">
                              <p>Prev Post</p>
                              <a href="#"><h4>A Discount Toner</h4></a>
                          </div>
                      </div>
                      <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                          <div class="detials">
                              <p>Next Post</p>
                              <a href="#"><h4>Cartridge Is Better</h4></a>
                          </div>
                          <div class="arrow">
                              <a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
                          </div>
                          <div class="thumb">
                              <a href="#"><img class="img-fluid" src="img/blog/next.jpg" alt=""></a>
                          </div>										
                      </div>									
                  </div>
            </div> -->
                <div class="comments-area">


                    <h4>{{blog.blog_comment.count}} Comments</h4>
                    <div class="comment-list">
                        {% for comment in blog.blog_comment.all  %}
                        <div class="single-comment justify-content-between d-flex">
                            <div class="user justify-content-between d-flex">
                                <!-- <div class="thumb">
                                    <img src="img/blog/c1.jpg" alt="">
                                </div> -->
                                <div class="desc">
                                    <h5><a href="#">@{{comment.user}}</a></h5>
                                    <p class="date">{{comment.comment_date}}</p>
                                    <p class="comment">
                                        {{comment.comment}} 
                                    </p>
                                </div>
                            </div>
                            <!-- <div class="reply-btn">
                                    <a href="" class="btn-reply text-uppercase">reply</a> 
                            </div> -->
                        </div>
                        {% endfor %}
                    </div>	
                </div>	                                             				
                <div class="comment-form">
                    <h4>Leave a Comment</h4>
                    <form method="POST">
                        <div class="form-group form-inline">
                          <div class="form-group col-lg-6 col-md-6 name">
                            {{comment_form}}
                            {% csrf_token %}
                          </div>										
                        </div>
                        <!-- <a href="#" class="button">Post Comment</a>	 -->
                        <button type="submit" class="button">Comment</button>
                    </form>
                </div>
            </div>

            <!--================================= Start Blog Post Siddebar ============================-->
            
            <div class="col-lg-4 sidebar-widgets">
                       <div class="widget-wrap">
                         <div class="single-sidebar-widget newsletter-widget">
                           <h4 class="single-sidebar-widget__title">Newsletter</h4>
                           <div class="form-group mt-30">
                             <div class="col-autos">
                               <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''"
                                 onblur="this.placeholder = 'Enter email'">
                             </div>
                           </div>
                           <button class="bbtns d-block mt-20 w-100">Subcribe</button>
                         </div>
           
           
                         <div class="single-sidebar-widget post-category-widget">
                           <h4 class="single-sidebar-widget__title">Catgory</h4>
                           <ul class="cat-list mt-20">
                             <li>
                               <a href="#" class="d-flex justify-content-between">
                                 <p>Technology</p>
                                 <p>(03)</p>
                               </a>
                             </li>
                             <li>
                               <a href="#" class="d-flex justify-content-between">
                                 <p>Software</p>
                                 <p>(09)</p>
                               </a>
                             </li>
                             <li>
                               <a href="#" class="d-flex justify-content-between">
                                 <p>Lifestyle</p>
                                 <p>(12)</p>
                               </a>
                             </li>
                             <li>
                               <a href="#" class="d-flex justify-content-between">
                                 <p>Shopping</p>
                                 <p>(02)</p>
                               </a>
                             </li>
                             <li>
                               <a href="#" class="d-flex justify-content-between">
                                 <p>Food</p>
                                 <p>(10)</p>
                               </a>
                             </li>
                           </ul>
                         </div>
           
                         <div class="single-sidebar-widget popular-post-widget">
                           <h4 class="single-sidebar-widget__title">Popular Post</h4>
                           <div class="popular-post-list">
                             <div class="single-post-list">
                               <div class="thumb">
                                 <img class="card-img rounded-0" src="img/blog/thumb/thumb1.png" alt="">
                                 <ul class="thumb-info">
                                   <li><a href="#">Adam Colinge</a></li>
                                   <li><a href="#">Dec 15</a></li>
                                 </ul>
                               </div>
                               <div class="details mt-20">
                                 <a href="blog-single.html">
                                   <h6>Accused of assaulting flight attendant miktake alaways</h6>
                                 </a>
                               </div>
                             </div>
                             <div class="single-post-list">
                               <div class="thumb">
                                 <img class="card-img rounded-0" src="img/blog/thumb/thumb2.png" alt="">
                                 <ul class="thumb-info">
                                   <li><a href="#">Adam Colinge</a></li>
                                   <li><a href="#">Dec 15</a></li>
                                 </ul>
                               </div>
                               <div class="details mt-20">
                                 <a href="blog-single.html">
                                   <h6>Tennessee outback steakhouse the
                                     worker diagnosed</h6>
                                 </a>
                               </div>
                             </div>
                             <div class="single-post-list">
                               <div class="thumb">
                                 <img class="card-img rounded-0" src="img/blog/thumb/thumb3.png" alt="">
                                 <ul class="thumb-info">
                                   <li><a href="#">Adam Colinge</a></li>
                                   <li><a href="#">Dec 15</a></li>
                                 </ul>
                               </div>
                               <div class="details mt-20">
                                 <a href="blog-single.html">
                                   <h6>Tennessee outback steakhouse the
                                     worker diagnosed</h6>
                                 </a>
                               </div>
                             </div>
                           </div>
                         </div>
           
                           <div class="single-sidebar-widget tag_cloud_widget">
                             <h4 class="single-sidebar-widget__title">Popular Post</h4>
                             <ul class="list">
                               <li>
                                   <a href="#">project</a>
                               </li>
                               <li>
                                   <a href="#">love</a>
                               </li>
                               <li>
                                   <a href="#">technology</a>
                               </li>
                               <li>
                                   <a href="#">travel</a>
                               </li>
                               <li>
                                   <a href="#">software</a>
                               </li>
                               <li>
                                   <a href="#">life style</a>
                               </li>
                               <li>
                                   <a href="#">design</a>
                               </li>
                               <li>
                                   <a href="#">illustration</a>
                               </li>
                             </ul>
                           </div>
                         </div>
            </div>

            <!--================================= End Blog Post Siddebar ==============================-->
        </div>
    </div>
</section>
<!--================ End Blog Post Area =================-->




{% endblock body_block %}

templates/Blog_App/blog_list.html
{% extends 'layouts/base.html' %}
{% load custom_filters %}
{% block title_block %} FOODIES - Blog {% endblock %}
{% block body_block %}
<section class="mb-30px">
    <div class="container">
      <div class="hero-banner hero-banner--sm">
        <div class="hero-banner__content">
            <h1> List of blogs</h1>
          <nav aria-label="breadcrumb" class="banner-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Blog Page</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>


<section class="blog-post-area section-margin">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="row">                    
                    {% for blog in blogs %}
                    <div class="col-md-4">
                        <div class="single-recent-blog-post card-view">
                            <div class="thumb">
                                <img class="card-img rounded-0" src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}">
                                <ul class="thumb-info">
                                    <li><a href="#"><i class="ti-user"></i><b>@{{blog.author}}</b> ({{ blog.publish_date }})</a></li>
                                    <!-- <li><a href="#"><i class="ti-themify-favicon"></i>{{ blog.publish_date }}</a></li> -->
                                </ul>
                            </div>
                            <div class="details mt-20">
                                <a href="blog-single.html">
                                <h3>{{ blog.blog_title }}</h3>
                                </a>
                                <p>{{blog.blog_content|striptags|range_filter|linebreaks}}</p>
                                <a class="button" href="{% url 'Blog_App:blog_details' slug=blog.slug %}">Read More <i class="ti-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>





{% endblock %}
    
    

templates/Blog_App/contact.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title_block %} FOODIES - Contact {% endblock %}

{% block body_block %}
  <!--================ Hero sm banner start =================-->  
  <section class="mb-30px">
    <div class="container">
      <div class="hero-banner hero-banner--sm">
        <div class="hero-banner__content">
          <h1>Contact Us</h1>
          <nav aria-label="breadcrumb" class="banner-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Contact Us</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
  <!--================ Hero sm banner end =================-->  


  <!-- ================ contact section start ================= -->
  <section class="section-margin--small section-margin">
    <div class="container">
      <div class="d-none d-sm-block mb-5 pb-4">
        <div id="map" style="height: 420px;"></div>
        <script>
          function initMap() {
            var uluru = {lat: 23.8223, lng: 90.3654}; // updated coordinates for Mirpur 10, Dhaka, Bangladesh
            var grayStyles = [
              {
                featureType: "all",
                stylers: [
                  { saturation: -90 },
                  { lightness: 50 }
                ]
              },
              {elementType: 'labels.text.fill', stylers: [{color: '#A3A3A3'}]}
            ];
            var map = new google.maps.Map(document.getElementById('map'), {
              center: uluru, // set center to uluru
              zoom: 15, // increase zoom for a closer view
              styles: grayStyles,
              scrollwheel: false
            });
            var marker = new google.maps.Marker({
              position: uluru,
              map: map,
              title: 'Mirpur 10, Dhaka, Bangladesh'
            });
          }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC9q1zAcUmT0F5KnE7s-AvjM0QCzcworxg&callback=initMap" async defer></script>
    </div>
    


      <div class="row">
        <div class="col-md-4 col-lg-3 mb-4 mb-md-0">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>Mirpur 10, Dhaka</h3>
              <p>Bangladesh</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-headphone"></i></span>
            <div class="media-body">
              <h3><a href="tel:454545654">+880-1521430255</a></h3>
              <p>Mon to Fri 9am to 6pm</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3><a href="mailto:shovonmufrid98@gmail.com">shovonmufrid98@gmail.com</a></h3>
              <p>Send us your query anytime!</p>
            </div>
          </div>
        </div>
        <div class="col-md-8 col-lg-9">
          <form action="#/" class="form-contact contact_form" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate">
            <div class="row">
              <div class="col-lg-5">
                <div class="form-group">
                  <input class="form-control" name="name" id="name" type="text" placeholder="Enter your name">
                </div>
                <div class="form-group">
                  <input class="form-control" name="email" id="email" type="email" placeholder="Enter email address">
                </div>
                <div class="form-group">
                  <input class="form-control" name="subject" id="subject" type="text" placeholder="Enter Subject">
                </div>
              </div>
              <div class="col-lg-7">
                <div class="form-group">
                    <textarea class="form-control different-control w-100" name="message" id="message" cols="30" rows="5" placeholder="Enter Message"></textarea>
                </div>
              </div>
            </div>
            <div class="form-group text-center text-md-right mt-3">
              <button type="submit" class="button button--active button-contactForm">Send Message</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
	<!-- ================ contact section end ================= -->

      
{% endblock body_block %}

templates/Blog_App/create_blog.html
{% extends 'layouts/base.html' %}


{% load crispy_forms_tags %}
{% block title_block %} FOODIES - Write Your Blog {% endblock %}
{% block body_block %}
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<section class="mb-30px">
    <div class="container">
<div class="p-3 m-auto">
<h2>Write Your Blog Here</h2>
<form action="" method="POST" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
    <br>
    <button type="submit" class="btn btn-success">Create Your Blog</button>
</form>
</div>
</div>
</section>










{% endblock body_block %}
        

templates/Blog_App/edit_blog.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} FOODIES - EDIT {% endblock %}
{% block body_block %}

<section class="mb-30px">
    <div class="container">
{% if blog.author == user    %}   

<form method="POST">
{{form|crispy}}
{% csrf_token %}
<button type="submit" class="btn btn-sm btn-danger" > Update </button>
{% else %}
<p>You Are Not Allowed To View This Page. 404</p>
</form>
{% endif %}
</div>
</section>



{% endblock body_block %}
        

templates/Blog_App/my_blogs.html
{% extends 'layouts/base.html' %} 
{% load custom_filters %}
{% block title_block %} FOODIES - {{user}}'s Blogs {% endblock title_block %} 

{% block body_block %}

<section class="mb-30px">
  <div class="container">
    {% for blog in user.post_author.all %}
    <h3>{{blog.blog_title}}</h3>
    <h6>{{blog.publish_date}}</h6>
    <div class="row">
      <div class="col-sm-4">
        <img
          src="/media/{{blog.blog_image}}"
          width="50%"
          alt="{{blog.blog_title}}"
        />
      </div>
      <div class="col-sm-8">
        <p>
          {{blog.blog_content|striptags|range_filter|linebreaks}}
          <a class="button mr-3" href="{% url 'Blog_App:blog_details' slug=blog.slug %}"
            >Read More</a>
            <a class="button" href="{% url 'Blog_App:edit_blog' slug=blog.slug %}">EDIT</a>
        </p>
      </div>
    </div>
    <hr>
    <!-- <div>
      <a class="button" href="{% url 'Blog_App:edit_blog' slug=blog.slug %}">EDIT</a>
    </div> -->
    {% endfor %} 
  </div>
</section>

{% endblock body_block %}