Blog_App/urls.py
from django.urls import path
from . import views

app_name = 'Blog_App'

urlpatterns = [
    path('', views.home, name="home"),
    path('contact/', views.contact, name="contact"),
    path('blogs/', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit/<slug>/', views.UpdateBlog.as_view(), name='edit_blog'),

]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
# for MEDIA
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('Login_App.urls')),
    path('', include('Blog_App.urls')),
    # path('', views.Index, name='index' )
]

# FOR MEDIA
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Login_App/urls.py
from django.urls import path
from . import views

app_name = 'Login_App'


urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('signin/', views.sign_in, name='signin'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('change/', views.user_change, name='change'),
    path('pass_change/', views.pass_change, name='pass_change'),
    path('add_picture/', views.add_pro_pic, name='add_picture'),
    path('picture_change/', views.change_picture, name='picture_change'),
]

templates/layouts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- <title>Sensive Blog - Home</title> -->
	<link rel="icon" href="img/Fevicon.png" type="image/png">

  <link rel="stylesheet" href="{% static 'assets/vendors/bootstrap/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/fontawesome/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/themify-icons/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/linericon/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel/owl.carousel.min.css' %}">
  <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
  <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <title>
        
    {% block title_block %}
       FOODIES - Home
    {% endblock %}
        
</title>


{% block css_block %}
  
{% endblock css_block %}
  
</head>

<body>
    
    {% include 'layouts/navbar.html' %}
    {% block body_block %}
        
    {% endblock body_block %}
    {% include 'layouts/footer.html' %}    





    <script src="{% static 'assets/vendors/jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'assets/vendors/bootstrap/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'assets/js/mail-script.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
  </body>
</html>

templates/layouts/footer.html
{% load static %}
<!--================ Start Footer Area =================-->
<footer class="footer-area section-padding">
    <div class="container">
      <div class="row">
        <div class="col-lg-3  col-md-6 col-sm-6">
          <div class="single-footer-widget">
            <h6>About Us</h6>
            <p>
             This site is made for the people who loves food and make foods with their creativity.
             You can share your own food experience to others through here.
            </p>
          </div>
        </div>
        <div class="col-lg-4  col-md-6 col-sm-6">
          <div class="single-footer-widget">
            <h6>Newsletter</h6>
            <p>Stay update with our latest</p>
            <div class="" id="mc_embed_signup">

              <form target="_blank" novalidate="true" action="#"
                method="get" class="form-inline">

                <div class="d-flex flex-row">

                  <input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
                    required="" type="email">


                  <button class="click-btn btn btn-default"><span class="lnr lnr-arrow-right"></span></button>
                  <div style="position: absolute; left: -5000px;">
                    <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                  </div>

                  <!-- <div class="col-lg-4 col-md-4">
                        <button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
                      </div>  -->
                </div>
                <div class="info"></div>
              </form>
            </div>
          </div>
        </div>
        <div class="col-lg-3  col-md-6 col-sm-6">
          <div class="single-footer-widget mail-chimp">
            <h6 class="mb-20">Instragram Feed</h6>
            <ul class="instafeed d-flex flex-wrap">
              <li><img src="{% static 'assets/img/instagram/i1.jpg'%}" alt=""></li>
              <li><img src="{% static 'assets/img/instagram/i2.jpg'%}" alt=""></li>
              <li><img src="{% static 'assets/img/instagram/i3.jpg'%}" alt=""></li>
              <li><img src="{% static 'assets/img/instagram/i4.jpg'%}" alt=""></li>
              <li><img src="{% static 'assets/img/instagram/i5.jpg'%}" alt=""></li>
              <li><img src="{% static 'assets/img/instagram/i6.jpg'%}" alt=""></li>
              <li><img src="{% static 'assets/img/instagram/i7.jpg'%}" alt=""></li>
              <li><img src="{% static 'assets/img/instagram/i8.jpg'%}" alt=""></li>

            </ul>
          </div>
        </div>
        <div class="col-lg-2 col-md-6 col-sm-6">
          <div class="single-footer-widget">
            <h6>Follow Us</h6>
            <p>Let us be social</p>
            <div class="footer-social d-flex align-items-center">
              <a href="#">
                <i class="fab fa-facebook-f"></i>
              </a>
              <a href="#">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="#">
                <i class="fab fa-dribbble"></i>
              </a>
              <a href="#">
                <i class="fab fa-behance"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
        <p class="footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Blog Site is made <i class="fa fa-user" aria-hidden="true"></i> by <a href="https://mufrid-shovon.netlify.app/" target="_blank">Mufrid Shovon</a>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
      </div>
    </div>
  </footer>
  <!--================ End Footer Area =================-->

templates/layouts/navbar.html
{% load static %}
<!--================Header Menu Area =================-->
<header class="header_area">
  <div class="main_menu">
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container box_1620">
        <!-- Brand and toggle get grouped for better mobile display -->
        <a class="navbar-brand logo_h" href="{% url 'Blog_App:home' %}">
          <!-- <img src="{% static 'assets/img/logo.png' %}" alt=""> -->
          <h1>FOODIES</h1>
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div
          class="collapse navbar-collapse offset"
          id="navbarSupportedContent"
        >
          <ul class="nav navbar-nav menu_nav justify-content-center">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Blog_App:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Blog_App:blog_list' %}">All Blogs</a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link" href="category.html">My Blogs</a>
            </li> -->
            <!-- <li class="nav-item submenu dropdown">
              <a
                href="#"
                class="nav-link dropdown-toggle"
                data-toggle="dropdown"
                role="button"
                aria-haspopup="true"
                aria-expanded="false"
                >Pages</a
              >
              <ul class="dropdown-menu">
                <li class="nav-item">
                  <a class="nav-link" href="blog-details.html">Blog Details</a>
                </li>
              </ul>
            </li> -->
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Blog_App:contact' %}">Contact</a>
            </li>
          </ul>
          {% if user.is_authenticated %}
          <div
            class="collapse navbar-collapse offset"
            id="navbarSupportedContent"
          >
            <ul class="nav navbar-nav menu_nav justify-content-center">
              <li class="nav-item submenu dropdown">
                <a
                  href="#"
                  class="nav-link dropdown-toggle"
                  data-toggle="dropdown"
                  role="button"
                  aria-haspopup="true"
                  aria-expanded="false"
                  ><h3 class="button">{{ user.username }}</h3></a
                >
                <ul class="dropdown-menu">
                  <li class="nav-item">
                    <a class="nav-link text-primary" href="{% url 'Login_App:profile' %}"
                      >My Profile</a
                    >
                  </li>
                  <li class="nav-item">
                    <a class="nav-link text-secondary" href="{% url 'Blog_App:create_blog' %}"
                      >Write Blogs</a
                    >
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'Blog_App:my_blogs' %}"
                      >My Blogs</a
                    >
                  </li>
                  <li class="nav-item">
                    <a class="nav-link text-danger" href="{% url 'Login_App:logout' %}"
                      >Log Out</a
                    >
                  </li>
                </ul>
              </li>
            </ul>
          </div>
          {% else %}
          <a class="btn btn-primary mr-3" href="{% url 'Login_App:signin' %}">Login</a>
          <a class="btn btn-success" href="{% url 'Login_App:signup' %}">Signup</a>
          {% endif %}   
          <!-- <ul class="nav navbar-nav navbar-right navbar-social">            
              <li><a href="#"><i class="ti-facebook"></i></a></li>
              <li><a href="#"><i class="ti-twitter-alt"></i></a></li>
              <li><a href="#"><i class="ti-instagram"></i></a></li>
              <li><a href="#"><i class="ti-skype"></i></a></li>
            </ul> -->
        </div>
      </div>
    </nav>
  </div>
</header>
<!--================Header Menu Area =================-->